Feature: Make sure we can only delete a map on the map database UI in RMXP mode #121
PokemonWorkshop/PokemonStudio pull request #133
Opened 2023-12-29 15:57 UTC by Palbolsky

## Description

This PR disables all features useless in the RMXP mode. The user can only delete maps.

## Note before testing

Pokémon Studio should be in RMXP mode. (edit the `project.studio` file if necessary)

## Tests to perform

- [ ] The user can't edit a map (MapFrame, MapAudio)
- [ ] The user can't start Tiled
- [ ] The user can't create a new map or a new folder (with the (+) button or 'New map' button)
- [ ] The user can't drag & drop in the map tree.
- [ ] Only the deleting option is present in the context menu.

2024-01-01 23:14 UTC, AerunDev requested changes
## Concernant les attendus de "Test to perform"
- [x] The user can't edit a map (MapFrame, MapAudio)
- [x] The user can't start Tiled
- [x] The user can't create a new map or a new folder (with the (+) button or 'New map' button)
- [x] The user can't drag & drop in the map tree.
- [x] Only the deleting option is present in the context menu.
- [x] The dbSymbol checking works correctly in the TypeNewEditor component
## Problèmes rencontrés lors des tests
- [x] Il est impossible d'éditer les informations d'une carte (MapFrame, MapAudio), que ce soit après avoir activé le mode Tiled depuis l'interface des paramètres de gestion des cartes (en étant donc auparavant en mode RMXP) ou en choisissant le mode Tiled dès la migration à la v2.0
- [x] "Ouvrir avec Tiled" dans le menu contextuel d'une carte ne fonctionne pas si on a activé le mode Tiled depuis le mode RMXP, alors que le bouton "Ouvrir avec Tiled" dans l'UI des données d'une carte fonctionne (et ce même si aucune map Tiled n'est liée)

2024-01-01 23:42 UTC, Palbolsky commented
> ## Problèmes rencontrés lors des tests
> * [ ]  Il est impossible d'éditer les informations d'une carte (MapFrame, MapAudio), que ce soit après avoir activé le mode Tiled depuis l'interface des paramètres de gestion des cartes (en étant donc auparavant en mode RMXP) ou en choisissant le mode Tiled dès la migration à la v2.0
> * [ ]  "Ouvrir avec Tiled" dans le menu contextuel d'une carte ne fonctionne pas si on a activé le mode Tiled depuis le mode RMXP, alors que le bouton "Ouvrir avec Tiled" dans l'UI des données d'une carte fonctionne (et ce même si aucune map Tiled n'est liée)

J'ai corrigé le premier problème, par contre je ne rencontre pas le deuxième problème que tu mentionnes.

2024-01-02 11:27 UTC, AerunDev commented
> J'ai corrigé le premier problème, par contre je ne rencontre pas le deuxième problème que tu mentionnes, à moins que tu es essayé d'utiliser le menu contextuel pour ouvrir Tiled avec une carte sans tiledFilename, car si c'est le cas il y avait déjà une sécurité (que j'ai amélioré car l'option n'apparaitra plus)

Oui c'est bien ça, il n'y avait pas de tiledFilename. Donc pas de souci au final ! Est-ce qu'on ne retirerait pas l'option du menu contextuel s'il n'y a pas de tiledFilename du coup ?

2024-01-02 12:53 UTC, Palbolsky commented
> Oui c'est bien ça, il n'y avait pas de tiledFilename. Donc pas de souci au final ! Est-ce qu'on ne retirerait pas l'option du menu contextuel s'il n'y a pas de tiledFilename du coup ?

C'est déjà fait ;)

2024-01-02 17:38 UTC, AerunDev approved these changes

2024-01-02 19:38 UTC, NuriYuri approved these changes

2024-01-02 20:41 UTC, merged