Improve the effect & status chance UX on the Moves UI
PokemonWorkshop/PokemonStudio pull request #141
Opened 2024-01-03 18:51 UTC by Zodiarche

## Tests to perform

- [ ] Hide the probability if you only have one status
- [ ] The probabilities change automatically according to the number of statuses.
- [ ] The same status cannot be entered more than once
- [ ] Nothing is displayed if you have no status
- [ ] Probabilities can only be changed if a status has been set.
- [ ] Setting none to one of the statuses will reset the following

## TODO :
- [ ] Do not overwrite custom values when opening the modal
- [ ] Display an error message depending on the problem
- [ ] Changing the display of chances

2024-01-07 10:29 UTC, NuriYuri commented on src/views/components/database/move/MoveStatus.tsx
> +type StatusKey = 'status_1' | 'status_2' | 'status_3';
```ts
const STATUS_KEY = ['status_1', 'status_2', 'status_3'] as const;
```

2024-01-07 10:29 UTC, NuriYuri commented on src/views/components/database/move/MoveStatus.tsx
> +              label={t(`status_${index + 1}` as StatusKey)}
`t(STATUS_KEY[index] || STATUS_KEY[0])`

2024-01-07 13:28 UTC, NuriYuri approved these changes

2024-01-07 14:01 UTC, Palbolsky commented
A voir si cela peut avoir une incidence, mais j'ai testé le cas suivant : 
- Attaque testée Poing Feu
- Mettre un deuxième statut
- Changer le pourcentage à 50% pour les deux statuts 
- Supprimer le deuxième statut
- Quitter
- Remettre un deuxième statut

On s'aperçoit que les 50% ont été sauvegardés et j'ignore si cela peut avoir un impact dans le calcul des probabilités.

Je pense qu'il faut aussi prévoir un texte indiquant qu'aucun statuts n'est défini (ça fait bizarre de voir un composant vide)

2024-01-07 20:53 UTC, Zodiarche commented
Non, ça met bien le premier à 100, c'est juste que quand tu rajoutes le 2ème, on met les 2 à 50.

2024-01-07 21:53 UTC, AerunDev requested changes
Je me permets une revue également après tests. Dans l'ensemble c'est top, mais je note plusieurs points à améliorer :
- [x] Il manque effectivement une indication "Aucun statut infligé" ou équivalente s'il n'y en a pas de paramétré. De manière générale il ne faut pas laisser l'utilisateur sans information.
- [ ] Je ne comprends pas l'intérêt du warning en rouge dans le cas d'un pourcentage à 0. Les chances sont toujours positives, donc si l'utilisateur met 0% et ferme le modal d'édition, on n'ajoute pas le statut à la liste et il recommencera. A la limite un compromis serait de mettre les chances en required avec un astérisque rouge, mais le warning reste confusant dans ce cas précis. On ne peut pas afficher une UI de ce genre avec un état en erreur par défaut.
- [x] Si je mets 150% dans l'input "Chance" d'un statut, j'ai le même message d'erreur qui s'affiche. On peut peut-être borner l'input entre 0 et 100 pour être sûr qu'on ne peut pas entrer de chance supérieure à 100 ?
- [x] "**La** somme de vos chances ne doi**ven**t pas excéder 100% **!**" -> "La somme de vos chances d'infliger un statut ne doit pas excéder 100%."
- [ ] Le design ne correspond pas à ce qui est sur l'issue ou sur Figma. Comme dit sur Discord la partie lecture du bloc doit afficher "Brûlure (10%)" avec le différentiel de couleur pour aider à la lisibilité.

2024-01-18 20:26 UTC, AerunDev requested changes
Suite à ce qu'on s'est dit sur Discord, je rajoute juste une dernière revue : 
- Il faut afficher "Statut" et non pas "Statut 1" dans le cas où il n'y a qu'un seul statut de visible,
- J'ai rencontré un bug quand je choisis 3 statuts différents : le bloc m'affiche toujours "Brûlure" (voir capture d'écran) : 

![image](https://github.com/PokemonWorkshop/PokemonStudio/assets/20935418/168354c1-79e9-4569-8967-8c41e5229e64)

2024-02-15 23:58 UTC, AerunDev approved these changes
Dernier test en date ! 😄 C'est nettement mieux, bien joué !
Pour ma part, je note une erreur de wording quand on a un input Chance à 0% dans le modal d'édition. On a "Les chances d'infliger un statut doit être compris entre 1 et 99." et ce serait plutôt "Les chances d'infliger un statut doivent être comprises entre 1 et 100."
![image](https://github.com/PokemonWorkshop/PokemonStudio/assets/20935418/1789c697-65ae-4232-8675-4394e623dc05)
Une fois la correction effectuée on pourra merge ! 😄

2024-02-16 00:07 UTC, merged