feat(textPage): navigate to pointed index and switch page
PokemonWorkshop/PokemonStudio pull request #2
Opened 2023-10-29 13:08 UTC by AntoinePoree

https://app.clickup.com/t/860q8wcjz

## As a User
I would like to translate a text right from the text list
So that I can easily translate it

Add a button at the end of the line that leads to the translation subpage and which set the index of this text.

### Acceptance 
- The user clicks on the button and is led to the translation subpage
- The user is led to the translation subpage and the right entry is displayed

2023-10-29 13:21 UTC, NuriYuri requested changes

2023-10-29 13:21 UTC, NuriYuri commented on src/views/pages/texts/Translation.page.tsx
> +  const redirectlocationState = () => {
Tu peux tenter de remplacer:
```ts
const [positionLanguage, setPositionLanguage] = useState<number>(1);
```

par
```ts
const { state } = useLocation();
const [positionLanguage, setPositionLanguage] = useState<number>(state?.position || 1);
```

Et supprimer le useEffect pour voir si ça marche également sans? (ça t'évitera d'avoir 2 renders si ça marche :))

2023-10-29 15:26 UTC, Palbolsky approved these changes
Pour moi c'est bon. GG :)

2023-10-29 15:59 UTC, AntoinePoree commented on src/views/pages/texts/Translation.page.tsx
> +  const redirectlocationState = () => {
En effet, ça fonctionne de la même manière comme cela, et c'est vraiment à l'initialisation que j'ai besoin de savoir si la data est passé, super retour ! 💯

2023-10-29 16:06 UTC, NuriYuri commented
Parfait, manque plus qu'un test :) 
Je sais pas si Palb a test donc j'approuve pas. N'oublie pas de sélectionner stash & merge quand tu mergera :)

2023-10-29 16:19 UTC, Palbolsky approved these changes
J'ai testé à nouveau avec les modifications apportées et c'est toujours bon. :)

2023-10-29 16:22 UTC, NuriYuri approved these changes

2023-10-30 22:23 UTC, AerunDev approved these changes

2023-10-30 22:23 UTC, AerunDev commented
Bien joué, c'est nickel ! 😄

2023-10-30 22:25 UTC, merged