Implement new select
PokemonWorkshop/PokemonStudio pull request #254
Opened 2024-03-09 15:29 UTC by NuriYuri

## Description

Ce code ajoute le composant Select selon les termes explicité sur la page: https://github.com/PokemonWorkshop/PokemonStudio/wiki/Select-as-input-tags

Aucune utilisation n'a été faite en dehors des exemples. Le but de cette PR est de s'accorder sur le code et ses exemple puis de merger dans le but de convertir les StudioDropDown / SelectXXX en ce qu'ils devraient être (ce Select).

## Note before testing

Vous pouvez accéder au design System depuis l'accueil de Pokémon Studio en cliquant sur le Logo. Vous trouverez les exemples dans l'onglet **Select**.

J'ai improvisé l'état disabled car il n'existe aucune définition de cette état à ce jour.

## Tests to perform

Tester tous les exemples pour s'assurer que ça correspond bien aux intentions du design system.

2024-03-10 14:10 UTC, Palbolsky commented
Testé et ça fonctionne bien, à part quelques points que j'ai relevé : 
- Quand on clique sur l'icône du select, le select ne s'ouvre pas (alors que si on clique autre part ça fonctionne)
- Lorsque le select est disable, le curseur de l'icône du select ne change pas
- Après avoir cliqué sur show value ou submit, je ne peux plus ouvrir de selects. Le bug se corrige si je défocus l'appli et que je reviens.

2024-03-10 14:21 UTC, NuriYuri commented
Le premier point est corrigé.

Pour le deuxième point, je suis pas sûr de bien comprendre. J'ai bien un curseur différent (flèche avec un signe interdit de stationner). Quelle est censé être l'icône du select dans un tel cas?

Pour le dernier point, c'est un soucis provenant de Windows pas de l'implémentation. Comme j'utilise alert la fenêtre se defocus donc les clics sont théoriquement plus capturés. Sous MacOS la fenêtre reprend automatiquement le focus donc /shrug. Dans tous les cas nous n'utiliserons pas alert() dans les faits, j'ai juste utilisé ça car nous n'avons pas de MessageBox (au sens où on fait un simple appel pour l'afficher).

2024-03-10 14:27 UTC, Palbolsky commented
> Pour le deuxième point, je suis pas sûr de bien comprendre. J'ai bien un curseur différent (flèche avec un signe interdit de stationner). Quelle est censé être l'icône du select dans un tel cas?

C'est simplement que la flèche avec un signe interdit de stationner ne se met pas sur l'icône du select. Mais tu l'as également corrigé quand tu as fix le premier point xD

2024-03-10 14:28 UTC, NuriYuri commented
Ah oui logique xD

J'avais juste pas compris xD

2024-03-10 14:31 UTC, Palbolsky approved these changes

2024-03-10 18:35 UTC, AerunDev requested changes
Yop ! La page du design system est cool, bien joué ! 😄 
Il faudra qu'on en parle à la prochaine réunion pour voir comment améliorer un peu l'organisation des infos et la façon d'y accéder. Pour l'instant ça fait son taff, clairement.
Bien joué sur les petites animations juicy sur la flèche du Select, ça donne son petit plus sympa !
## Tests fonctionnels
Concernant le test en lui même, j'ai un cas assez contraignant qui me force à défocus l'application et à y revenir pour pouvoir utiliser les Select à nouveau. Un cas de reproduction en suivant ces étapes :
- J'accède à la page du Design System.
- Je clique sur "Show Value" sur le dernier Select affichant "Option 1023" au départ. Une dialog affichant la valeur Value: value_1023 s'ouvre.
- Je clique sur "OK".
- Les Select sont alors comme désactivés.
- Je quitte le focus de l'application, je reviens dessus. Tout refonctionne.

Peut-être juste lié à ces boutons de test ?

Quand je clique sur l'icône du Select, ça ne l'ouvre pas. J'ai l'impression qu'on perd le hover quand on est sur l'icône, l'encadré disparaît. C'était le cas avant sur l'ancien, et c'est assez gênant. Par contre, si je clique sur l'icône alors qu'il est ouvert ça fonctionne bien ! 😄 
## Retours sur le design
J'ai noté quelques améliorations en terme de Design, surtout pour ne pas apporter de régression dans le design déjà existant :
- Le texte de la valeur de la donnée doit être en text400 pour les Select à l'état par défaut, qu'on ait sélectionné une valeur ou non. En text100 il est trop visible et rompt la hiérarchie visuelle de l'information. [Cf. un exemple sur Figma.](https://www.figma.com/file/xglOHHLb96zfPMTXd3v8i9/Pok%C3%A9mon-Studio?type=design&node-id=4643-9039&mode=design&t=NZXTh1leLeOWrWVc-4)
- Pour le style du hover clavier foncé, il me paraît un peu trop proche du fond de la liste, est-ce que c'est bien du `dark16` ?
- Dans le cas où on a aucune valeur sélectionnée, si on clique sur le Select, la première valeur est en hover foncé. On ne pourrait pas avoir le hover clair par défaut ? Ce serait plus visible, le hover foncé étant vraiment réservé au focus clavier si on change pour bien différencier avec le hover souris.
- L'espacement entre le Select et la boîte de la liste des éléments est trop petit. Actuellement il est de 3px, Il faudrait mettre 6 ou 8px. Précédemment nous étions à 6px, mais pas sûr que ça soit en accord avec le principe du spacing multiple de 4px. @Walven tu as un avis sur ça ?
- La boîte de la liste des éléments est décalée d'un pixel de trop vers la droite, ce qui créé un léger déséquilibre visuel. C'est très subtile mais c'est assez visible quand même.
- La scroll bar devrait être alignée avec le premier et le dernier élément de la liste. Pour référence l'ancien, et un screen.
![Capture d'écran 2024-03-10 185641](https://github.com/PokemonWorkshop/PokemonStudio/assets/20935418/7a69aa62-ff50-4ab2-bf11-499b9f6cb957)

Si besoin de précision, on peut faire un vocal dans la journée de demain, ou un soir dans la fin de semaine ! 😄

2024-03-10 19:03 UTC, NuriYuri commented
> Quand je clique sur l'icône du Select, ça ne l'ouvre pas. J'ai l'impression qu'on perd le hover quand on est sur l'icône, l'encadré disparaît. C'était le cas avant sur l'ancien, et c'est assez gênant. Par contre, si je clique sur l'icône alors qu'il est ouvert ça fonctionne bien ! 😄

Est-ce que tu es bien sur la bonne version? (Je comprends bien bien le problème tbh, l'icône c'est quoi? Quand je clique sur le chevron, le select s'ouvre bien, j'ai bien les effet de hover, etc...)

> Le texte de la valeur de la donnée doit être en text400

My bad, j'ai mal choisi ^^
Il faudra penser à une valeur pour le placeholder (aucun choix fait).

> Pour le style du hover clavier foncé

C'était dark18, je change en 16 ça rend mieux.

> L'espacement entre le Select et la boîte de la liste des éléments est trop petit

C'était 4px j'ai passé à 7px. (variable `SELECT_SPACING`)

> La boîte de la liste des éléments est décalée d'un pixel de trop vers la droite

J'ai ajusté `POPOVER_ADJUSTMENT` à 12 en espérant que ça marche assez bien ^^

> La scroll bar devrait être alignée avec le premier et le dernier élément de la liste

J'avais volé le style ailleurs, j'ai fait un ajustement (margin top et bottom à 3px pour la scrollbar). J'espère que c'est suffisant ^^

2024-03-10 19:58 UTC, AerunDev commented
> Est-ce que tu es bien sur la bonne version? (Je comprends bien bien le problème tbh, l'icône c'est quoi? Quand je clique sur le chevron, le select s'ouvre bien, j'ai bien les effet de hover, etc...)

J'étais sûrement sur le mauvais commit ! J'avais pourtant fetch, c'est étrange. En tout cas c'est bien corrigé donc n'y fais plus attention.

> Il faudra penser à une valeur pour le placeholder (aucun choix fait).

Pour le placeholder text400 c'est parfait. Je pense que ce sera revu avec le nouveau Design System, jusque là on a eu aucun retour sur ce choix donc on peut garder la même chose.

> C'était 4px j'ai passé à 7px. (variable `SELECT_SPACING`)
> J'ai ajusté `POPOVER_ADJUSTMENT` à 12 en espérant que ça marche assez bien ^^

Ok je pense comprendre ce qui a mené à ces décalages et variations : le contour des boîtes en hover et active est de 1.5px au lieu de 2px, et situé à l'extérieur au lieu d'une bordure interne. Du coup ça décale les éléments de 1px.

> J'avais volé le style ailleurs, j'ai fait un ajustement (margin top et bottom à 3px pour la scrollbar). J'espère que c'est suffisant ^^

Oui c'est parfait comme ça, bien joué ! On chipoterait à mettre 2px de margin top et bottom pour que ce soit pixel perfect mais osef, ça passe très bien.

2024-03-10 20:14 UTC, NuriYuri commented
> le contour des boîtes en hover et active est de 1.5px au lieu de 2px, et situé à l'extérieur au lieu d'une bordure interne

Oui j'ai remarqué d'ailleurs que ça a tendance à baver sur les parents qui n'ont pas de padding. Faudra qu'on évite les éléments à taille variable (outline qui change entre 0 et n px) à l'avenir :) (Concrètement, privilégier les border et utiliser la couleur courante/transparente si on veut pas de bordure sur les autres états)

2024-03-10 20:39 UTC, AerunDev commented
> Oui j'ai remarqué d'ailleurs que ça a tendance à baver sur les parents qui n'ont pas de padding. Faudra qu'on évite les éléments à taille variable (outline qui change entre 0 et n px) à l'avenir :) (Concrètement, privilégier les border et utiliser la couleur courante/transparente si on veut pas de bordure sur les autres états)

Oui c'est normalement l'attendu d'avoir la même bordure à 2px. Elle est transparente par défaut et visible en hover / active.

2024-03-10 21:51 UTC, AerunDev commented
Je viens de remarquer un petit outline autour de la zone de texte de l'Input dans les Select déjà existants.
Je préfère le signaler au cas où : 
![image](https://github.com/PokemonWorkshop/PokemonStudio/assets/20935418/cdc6fb7c-2408-4b83-89e2-0c7c8e4c3078)

2024-03-11 13:43 UTC, NuriYuri commented
C'était un side effect d'un changement que j'avais fait en symétrie entre input et Input. Je l'ai retiré pour le moment :)
(Ca devrait mieux rendre).

2024-03-12 11:41 UTC, AerunDev approved these changes

2024-03-12 16:22 UTC, merged