Set min max on inputs
PokemonWorkshop/PokemonStudio pull request #258
Opened 2024-03-11 12:06 UTC by Zodiarche

J'aurai besoin d'aide pour limiter l'input d'évolution du pokémon, je ne trouve pas ou c'est.

- [ ] Le poids va de 0.01 à 1000
- [ ] La taille va de 0.01 à 100
- [ ] L'expérience de base va de 0 à 1000
- [ ] Les chances d'être female vont de 0 à 100
- [ ] Le catch rate va de 1 à 255
- [ ] Le hatch step va de 0 à 99999

2024-03-11 12:09 UTC, AerunDev commented
Tu peux reprendre le template de PR et éditer ta description ? 😄 
Pour ta demande d'aide je pense que tu auras plus de chance d'avoir une réponse sur Discord car en description de PR on s'attend pas à voir des questions.

2024-03-12 16:22 UTC, NuriYuri approved these changes

2024-03-13 10:39 UTC, Zodiarche commented
J'ai également mis à jour le package-lock.js, notamment en réglant une vulnérabilité qu'on avait avec audit.

2024-03-13 14:37 UTC, Palbolsky commented
GG pour la PR. J'ai fait un test et je suis tombé sur quelques "problèmes" :

![image](https://github.com/PokemonWorkshop/PokemonStudio/assets/7809685/70b45040-b0b2-476e-aadb-78eb4fb05a85)
On ne peut pas sortir du composant si on a pas défini de valeur, alors que ça doit mettre par défaut la valeur qui était présente avant édition.

Dans le composant qui gère le taux de femelle, lorsqu'on met Asexué à false, le taux de femelle est à -1 dans l'input. Je pense qu'il faudrait mettre 0 par défaut pour avoir une valeur valide.
Toujours dans le même composant, si on quitte le composant en ayant supprimé la chance d'un objet, cela ne remet pas la chance qu'on avait avant édition mais 0.

Même problème que mentionner précédement pour les statistiques.

2024-03-19 20:02 UTC, Zodiarche commented
J'ai fini la tâche (normalement), juste un soucis avec dialogRef que j'ai mis en commentaire pour le moment, le temps de trouver la solution

2024-03-19 20:49 UTC, NuriYuri commented
Quel est le soucis au juste?
(A voir pour logger les valeurs histoire de voir si c'est bien valorisé)

2024-03-22 14:06 UTC, Palbolsky approved these changes

2024-03-24 21:22 UTC, AerunDev requested changes
Je me suis lancé sur un test, et j'ai un bug bloquant sur le PokedexEditor seulement :
- Je vais sur la page de Bulbizarre
- Je tente de mettre 999 au poids en kg
- Je ne peux plus quitter l'éditeur, sans aucune erreur ni indication du problème
- Spammer ECHAP permet de quitter le dialog d'édition, qui semble garder en mémoire le 999, mais ça ne se répercute ni dans le data visible sur la page du Pokémon, ni sur la state (pas de bouton de save disponible)

Après deuxième test, rien qu'ouvrir le modal d'édition du bloc Pokédex oblige à spammer ECHAP. Et tant qu'on ne va pas sur une autre page les raccourcis claviers CTRL + DROITE/GAUCHE sont bloqués également. On est obligé d'aller sur la page des attaques puis de revenir sur Bulbizarre pour que ça se débloque.

2024-03-25 21:14 UTC, Zodiarche commented
> Je me suis lancé sur un test, et j'ai un bug bloquant sur le PokedexEditor seulement :
> 
>     * Je vais sur la page de Bulbizarre
> 
>     * Je tente de mettre 999 au poids en kg
> 
>     * Je ne peux plus quitter l'éditeur, sans aucune erreur ni indication du problème
> 
>     * Spammer ECHAP permet de quitter le dialog d'édition, qui semble garder en mémoire le 999, mais ça ne se répercute ni dans le data visible sur la page du Pokémon, ni sur la state (pas de bouton de save disponible)
> 
> 
> Après deuxième test, rien qu'ouvrir le modal d'édition du bloc Pokédex oblige à spammer ECHAP. Et tant qu'on ne va pas sur une autre page les raccourcis claviers CTRL + DROITE/GAUCHE sont bloqués également. On est obligé d'aller sur la page des attaques puis de revenir sur Bulbizarre pour que ça se débloque.

C'est corrigé !

2024-03-25 21:34 UTC, AerunDev commented
Effectivement bien joué, tout est bon ! 😄 
J'ai par contre découvert un nouveau bug (et même un crash cette fois-ci) dans le cas où on affiche un Pokémon qui a dans son JSON un tableau itemHeld vide, et qu'on clique sur le bloc "Rencontre" qui contient les objets portés.

![image](https://github.com/PokemonWorkshop/PokemonStudio/assets/20935418/6f93c5e8-3645-4047-b744-5649f875948e)

C'est le cas notamment de pas mal de Méga-Evolutions sur la démo technique, comme la forme 30 de Blizzaroi. Ça semblait être autorisé avant, ou en tout cas ça ne crashait pas.
J'ai vérifié en 2.0.3 et le comportement dans ce cas c'était de remplir les inputs avec 0%, ce qui comptait comme une modification pour éviter de sortir du modal avec des données vides.

2024-03-30 11:14 UTC, NuriYuri commented
J'ai fait un commit qui devrait en théorie corriger le problème.

Je tiens juste à pointer que les lignes du screenshot et les lignes dans le code ne correspondent pas. Ca peut potentiellement indiquer un test sur le mauvais commit.

2024-03-30 15:24 UTC, Palbolsky commented
J'ai ajouté un petit fix supplémentaire dans la continuité du fix de Yuri.

2024-03-31 12:56 UTC, Palbolsky approved these changes

2024-04-01 11:51 UTC, AerunDev approved these changes

2024-04-01 11:52 UTC, merged