fix: make JSON more easy to debug
PokemonWorkshop/PokemonStudio pull request #271
Opened 2024-03-24 18:26 UTC by AntoinePoree

## Description
Add:
- Invalid Json will emit the file who crash
- Line break on modal error

Close: https://github.com/PokemonWorkshop/PokemonStudio/issues/253

## Tests to perform

- [ ] When a Json is fucked, i get a model with the name of file who crashed

2024-03-26 20:05 UTC, NuriYuri commented on .vscode/settings.json
> +  "editor.formatOnSave": false,
?

2024-03-26 22:14 UTC, Palbolsky commented on .vscode/settings.json
> +  "editor.formatOnSave": false,
Pourquoi ce changement ? C'est ce qui nous assure quand on sauvegarde que le fichier est correctement formaté.

2024-04-14 11:18 UTC, AntoinePoree commented on .vscode/settings.json
> +  "editor.formatOnSave": false,
Hum, je vois pas pourquoi cela a été commit :c

2024-04-14 11:59 UTC, AntoinePoree commented on .vscode/settings.json
> +  "editor.formatOnSave": false,
Bon, c'est parce que localement, j'avais retiré le formatOnSave, sauf que votre projet le force avec cette ligne, elle a dû etre changé automatiquement ducoup.

2024-04-14 12:23 UTC, NuriYuri approved these changes

2024-04-23 12:05 UTC, Palbolsky requested changes

2024-04-23 12:05 UTC, Palbolsky commented on src/backendTasks/checkMapsModified.ts
> +  const studioMaps: StudioMapBackend[] = payload.maps.map((map) => parseJSON(map, map));
Ici tu peux laisser JSON.parse parce que les données viennent du front (en plus tu mets 2 fois map alors que le deuxième argument est pour le filename)

2024-04-24 11:54 UTC, Palbolsky approved these changes

2024-04-24 22:54 UTC, AerunDev approved these changes
Testé et fonctionnel ! 😄

2024-04-24 22:54 UTC, merged