Feature: Implement an UI component for the user onboarding flow
PokemonWorkshop/PokemonStudio pull request #272
Opened 2024-03-25 23:55 UTC by Palbolsky

## Description

This PR adds an user onboarding flow.
Closes: https://github.com/PokemonWorkshop/PokemonStudio/issues/187

## Tests to perform

- [ ] Check that buttons do the right thing
- [ ] Check that step management works
- [ ] Check that the style is correct

2024-03-26 20:02 UTC, NuriYuri approved these changes

2024-03-26 21:36 UTC, AerunDev requested changes
C'est franchement top ! 😄 

J'ai deux remarques à soulever, et je te propose d'en discuter avant de merge :
- Quand on clique sur "J'ai compris" dans le bloc 3/3, à mon sens le bouton ne devrait plus être actif. Contrairement aux deux autres, ce bouton n'est plus utile.
- Au niveau du bouton à l'état "Current", je pense qu'on peut mieux faire vis à vis de la couleur du Hover, car bien que ça colle à ce qui est sur Figma je ne trouve pas ça super esthétique. @Walven tu as peut-être une idée pour une amélioration en attendant le DS ?

2024-03-26 22:04 UTC, Palbolsky commented
J'ai apporté le changement pour le premier point.
En ce qui concerne le deuxième, j'attends une solution :)

2024-04-01 23:00 UTC, AerunDev approved these changes

2024-04-01 23:00 UTC, merged