Add a way to set the volume and the pitch of the maps
PokemonWorkshop/PokemonStudio pull request #274
Opened 2024-03-31 00:39 UTC by Palbolsky

## Description

This PR allows the user to change the volume and pitch of the cards. 
This PR is linked to a PSDK MR: https://gitlab.com/pokemonsdk/pokemonsdk/-/merge_requests/1299

Closes: https://github.com/PokemonWorkshop/PokemonStudio/issues/243

## Note before testing

The project should be in 2.0.3 Studio version and migrate in 2.0.4 version (development version).

## Tests to perform

- [ ] Check that change the music data in Studio is converted in RMXP (don't forget to launch PSDK)

2024-04-08 21:36 UTC, AerunDev requested changes
Beau boulot ! 😄 
Testé partiellement* ce soir :
- Migration ✅
- J'ai remarqué un problème en utilisant l'input du volume de la Background Music (BGM) d'une map : on ne peut pas utiliser HAUT / BAS pour défiler dans l'input de 0 à 100, alors qu'on peut le faire pour le pitch. Il semblerait qu'il manque un `type="number"` pour le volume, non ? J'ai testé de le rajouter de mon côté et ça semble corriger le problème.

*Petite revue car il se fait tard pour moi mais je continuerai demain soir pour tester plus avant.

2024-04-08 21:45 UTC, Palbolsky commented
> * J'ai remarqué un problème en utilisant l'input du volume de la Background Music (BGM) d'une map : on ne peut pas utiliser HAUT / BAS pour défiler dans l'input de 0 à 100, alors qu'on peut le faire pour le pitch. Il semblerait qu'il manque un `type="number"` pour le volume, non ? J'ai testé de le rajouter de mon côté et ça semble corriger le problème.

Bien vu :D C'est corrigé.

2024-04-09 21:34 UTC, AerunDev approved these changes

2024-04-17 14:32 UTC, NuriYuri approved these changes

2024-04-17 19:24 UTC, merged