Fix party_length_limit display
PokemonWorkshop/PokemonStudio pull request #348
Opened 2024-07-01 18:04 UTC by Zodiarche

## Description

When importing certain trainers, the tooltip was displayed without being intended to do so.

## Tests to perform

- Take a trainer with 1 Pokemon, import the Pokemon of a trainer with 5 Pokemon

2024-07-01 18:43 UTC, Palbolsky commented
J'ai réussi à reproduire le problème, mais le fix ne me semble pas bon car maintenant le tooltip ne pourra jamais s'afficher car la condition `trainer.party.length > 6` ne sera jamais valide.

Le code de base sans changement est presque bon, le problème ce n'est pas la condition mais le tooltip qui se refresh trop vite et prend en compte les Pokémon qui viennent d'être ajoutés.
La solution est de faire en sorte que la fonction `canImport` utilise un clone de trainer qui est cloné à l'ouverture de l'éditeur mais plus modifié après de sorte que lorsqu'on ajoute les Pokémon dans le dresseur, le clone ne subit pas le changement et le tooltip ne s'affichera pas.

2024-07-02 19:17 UTC, NuriYuri commented on src/views/components/pokemonBattler/editors/PokemonBattlerImport.tsx
Je vois ce que palb pense.

Tu dois faire la chose suivante:
Après la ligne: `const updateTrainer = useUpdateTrainer(trainer);`
Ajoute: `const currentTrainer = useMemo(() => cloneEntity(trainer), []);`

Partout après cette ligne, remplace `trainer` par `currentTrainer`, ça devrait corriger le problème sans le fix que t'as tenté :)

2024-07-03 07:55 UTC, Zodiarche commented
Je vois ce que vous voulez dire, mais j'ai l'impression que dans tous les cas cette vérification est un peu inutile car le plus important c'est d'empêcher l'importation, pas de vérifier après l'importation, et on a déjà une sécurité sur l'importation en elle-même, on ne pouvait juste pas enlever cette logique au final ?

2024-07-03 16:45 UTC, Palbolsky requested changes

2024-07-03 16:45 UTC, Palbolsky commented on src/views/components/pokemonBattler/editors/PokemonBattlerImport.tsx
> +          <TooltipWrapper data-tooltip={dropDownSelection === 'default' && !canImport ? tTrainer('party_length_limit') : undefined}>
Petit typo ici, c'est `!canImport(override)` (sinon la fonction est pas appelée ^^')

2024-07-03 16:51 UTC, Palbolsky commented
> Je vois ce que vous voulez dire, mais j'ai l'impression que dans tous les cas cette vérification est un peu inutile car le plus important c'est d'empêcher l'importation, pas de vérifier après l'importation, et on a déjà une sécurité sur l'importation en elle-même, on ne pouvait juste pas enlever cette logique au final ?

Tu as un bouton disabled, donc il faut informer l'utilisateur pourquoi il n'est pas utilisable, donc on a besoin du tooltip.
On ne veut pas vérifier ce qui se passe après l'importation, mais c'est ce que faisait le code (bien que c'était pas voulu), d'où le tooltip qui s'affichait à la fermeture de l'éditeur. C'est pour ça qu'en clonant on évite ce problème, on met à jour le dresseur quand on importe, mais pas le clone donc ça évite que le canImport se trigger pour rien.

2024-07-04 20:24 UTC, Palbolsky approved these changes

2024-07-05 22:01 UTC, AerunDev approved these changes
Testé et ça fonctionne nickel, bien joué !

2024-07-05 22:08 UTC, merged