Fix a bug with the project names that are too long in the Studio's home project card component
PokemonWorkshop/PokemonStudio pull request #354
Opened 2024-07-08 18:13 UTC by Zodiarche

## Description

When the user is setting a project name that is too long, the name is not properly displayed in the recent project card component.

## Note before testing

- Are we sure of the styles used in this component? Because I do a lot of CSS in my everyday life, I've seen and tested a few things locally and I've noticed that some styles aren't useful.

## Steps to reproduce
- Create a project
- Change the name for a long one like "my-super-monster-taming-game-project-for-real"
- Check the home's recent project component for this project

2024-07-08 23:01 UTC, AerunDev requested changes
Ça ne va pas. Avec ces modifications je me retrouve avec potentiellement des ProjectCard qui peuvent avoir une taille infinie, hors on veut que la taille soit fixe.
Il vaudrait mieux ajouter un ellipsis si le nom dépasse, comme pour le chemin du projet.

2024-07-11 17:17 UTC, Zodiarche commented
> Ça ne va pas. Avec ces modifications je me retrouve avec potentiellement des ProjectCard qui peuvent avoir une hauteur infinie, or on veut que la taille soit fixe. Il vaudrait mieux ajouter un ellipsis si le nom dépasse, comme pour le chemin du projet. Et un Tooltip si ellipsis également.
> 
> Par exemple : ![image](https://private-user-images.githubusercontent.com/20935418/346745800-788c46a1-c81d-44e7-acc9-2437081aec4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MTg1MTQsIm5iZiI6MTcyMDcxODIxNCwicGF0aCI6Ii8yMDkzNTQxOC8zNDY3NDU4MDAtNzg4YzQ2YTEtYzgxZC00NGU3LWFjYzktMjQzNzA4MWFlYzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDE3MTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYjEyZTQ0NzU1YmUwY2EyMjVjMDIxZDc3ODhmM2Q3ODM4MzYwYmQzNmViZDI1OTE3YjdkYzQxZTNhNjNjNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QXnJfu3KvJ511QvOfu7glnm4S5WdZqdAVyi_Wz8RL5E)

ça marche, je remettrai comme c'était et rajouterai uniquement le tooltip du coup, de la même manière qu'à le path.

2024-07-11 19:33 UTC, Zodiarche commented
Je comprends pas par contre pour le path a bien le tooltip mais pas le titre du coup

2024-07-11 19:37 UTC, Zodiarche commented
> Je comprends pas par contre pour le path a bien le tooltip mais pas le titre du coup

RAS, j'ai trouvé, j'suis bête

2024-07-11 19:40 UTC, Zodiarche commented
ça convient ?

![image](https://github.com/PokemonWorkshop/PokemonStudio/assets/81259986/a73b3812-ff1c-430f-91ce-e67c443a30a0)

2024-07-11 19:41 UTC, AerunDev commented
> ça convient ?
> 
> ![image](https://private-user-images.githubusercontent.com/81259986/347970058-a73b3812-ff1c-430f-91ce-e67c443a30a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MjcxMDksIm5iZiI6MTcyMDcyNjgwOSwicGF0aCI6Ii84MTI1OTk4Ni8zNDc5NzAwNTgtYTczYjM4MTItZmYxYy00MzBmLTkxY2UtZTY3YzQ0M2EzMGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDE5NDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MDE5ODExMDYzZDJmNGVjODNmYjM4Yzg4MWRmZjZlODQwY2Q4YjNiOWQxYjIwMGY0ZWQ5YTljYTIzYTAzZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zBljKnUNBEMzT_rxJXueMToCIuJwNe3AwZkv1nsLSBg)

Il manque le "..." à la fin pour bien faire comprendre que ça dépasse du cadre.

2024-07-11 19:42 UTC, Zodiarche commented
> > ça convient ?
> > ![image](https://private-user-images.githubusercontent.com/81259986/347970058-a73b3812-ff1c-430f-91ce-e67c443a30a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MjcxMDksIm5iZiI6MTcyMDcyNjgwOSwicGF0aCI6Ii84MTI1OTk4Ni8zNDc5NzAwNTgtYTczYjM4MTItZmYxYy00MzBmLTkxY2UtZTY3YzQ0M2EzMGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDE5NDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MDE5ODExMDYzZDJmNGVjODNmYjM4Yzg4MWRmZjZlODQwY2Q4YjNiOWQxYjIwMGY0ZWQ5YTljYTIzYTAzZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zBljKnUNBEMzT_rxJXueMToCIuJwNe3AwZkv1nsLSBg)
> 
> Il manque le "..." à la fin pour bien faire comprendre que ça dépasse du cadre.

Oui exact, mais je parlais surtout de la logique de passer de "sur 2 lignes" à une ligne avec tooltip

2024-07-11 20:23 UTC, AerunDev commented
Ce n'est pas possible de conserver 2 lignes et le "..." si ça dépasse, je suppose ?

2024-07-11 20:23 UTC, Zodiarche commented
Pas à ma connaissance

2024-07-12 15:57 UTC, Palbolsky approved these changes

2024-07-12 19:05 UTC, AerunDev approved these changes

2024-07-12 19:06 UTC, NuriYuri commented
Essaie: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp

2024-07-12 19:07 UTC, AerunDev commented
Visiblement il existe une possibilité d'avoir deux lignes et un ellipsis à la fin, mais comme on a le Tooltip sur le `white-space: nowrap;` ce ne sera pas possible de notre côté, effectivement.
source : https://stackoverflow.com/questions/3922739/limit-text-length-to-n-lines-using-css

Pour moi c'est nickel, je dirais juste de refacto (si je ne fais pas fausse route) :
```css
overflow-x: hidden;
overflow-y: hidden;
```
en :
```css
overflow: hidden;
```

2024-07-12 19:08 UTC, Zodiarche commented
Oui, je n'avais pas fait gaffe au -y plus haut

2024-07-12 20:43 UTC, Zodiarche commented
> Essaie: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp

J'ai déjà testé ça, mais on ne peut pas avec le white-space

2024-07-12 20:50 UTC, merged