Make sure that the user can use the Showdown import even if there is no trainer in the database
PokemonWorkshop/PokemonStudio pull request #355
Opened 2024-07-08 20:39 UTC by Zodiarche

## Description

When you have only one trainer in Studio, it is now possible to use the import only in Showdown mode.

## Tests to perform

- Having only one trainer
- [ ] It is not possible to change mode
- [ ] An error message appears when you try to change modes when you have no trainers to import.
- [ ] Import when at least two trainers are working as intended

2024-07-10 21:02 UTC, AerunDev requested changes
Je viens de tester ta PR ! 😄 
Sur le fond ça fonctionne bien, mais j'ai quelques remarques sur la forme et l'UX car avec la proposition actuelle on perd un peu l'utilisateur.

- On affiche l'erreur sur l'input "Code au format Showdown" alors qu'elle devrait s'afficher sous le dropdown "Importer les Pokémon" vu que c'est la sélection dans cette liste qui est problématique.
- Si tu n'as qu'un seul dresseur, et que tu as la condition pour afficher l'erreur si on sélectionne "D'un autre dresseur", il vaudrait mieux soit masquer la liste déroulante "Importer les Pokémon" pour éviter qu'on ne soit tenter de le sélectionner alors que ce n'est pas possible, soit la disable pour faire comprendre qu'il n'y a qu'un choix possible.

2024-07-11 17:16 UTC, Zodiarche commented
> Je viens de tester ta PR ! 😄 Sur le fond ça fonctionne bien, mais j'ai quelques remarques sur la forme et l'UX car avec la proposition actuelle on perd un peu l'utilisateur.
> 
> * On affiche l'erreur sur l'input "Code au format Showdown" alors qu'elle devrait s'afficher sous le dropdown "Importer les Pokémon" vu que c'est la sélection dans cette liste qui est problématique.
> * Si tu n'as qu'un seul dresseur, et que tu as la condition pour afficher l'erreur si on sélectionne "D'un autre dresseur", il vaudrait mieux soit masquer la liste déroulante "Importer les Pokémon" pour éviter qu'on ne soit tenter de le sélectionner alors que ce n'est pas possible, soit la disable pour faire comprendre qu'il n'y a qu'un choix possible.

Yes je me doutais à l'avance qu'il y aurait des choses à revoir, j'ai surtout "balancé" une base de travail fonctionnel pour qu'on voit ensemble derrière le visuel qu'on veut lui donner.

2024-07-11 19:00 UTC, NuriYuri approved these changes

2024-07-11 20:09 UTC, Zodiarche commented
> Je viens de tester ta PR ! 😄 Sur le fond ça fonctionne bien, mais j'ai quelques remarques sur la forme et l'UX car avec la proposition actuelle on perd un peu l'utilisateur.
> 
> * On affiche l'erreur sur l'input "Code au format Showdown" alors qu'elle devrait s'afficher sous le dropdown "Importer les Pokémon" vu que c'est la sélection dans cette liste qui est problématique.
> * Si tu n'as qu'un seul dresseur, et que tu as la condition pour afficher l'erreur si on sélectionne "D'un autre dresseur", il vaudrait mieux soit masquer la liste déroulante "Importer les Pokémon" pour éviter qu'on ne soit tenter de le sélectionner alors que ce n'est pas possible, soit la disable pour faire comprendre qu'il n'y a qu'un choix possible.

J'ai corrigé en préférant cacher, je me dit que c'est le mieux, je laisse quand même le message d'erreur dans les textes si on en a besoin un jour ?

2024-07-12 16:05 UTC, Palbolsky commented
J'ai trouvé un crash pour l'import des Pokémon dans les groupes.

![image](https://github.com/user-attachments/assets/be76d94e-9c5e-406b-8836-4590467c4ffc)

Reproduction : 
- Dans la page d'un groupe, cliquer sur "Importer une liste de Pokémon",
- Pour le select "Importer les Pokémon", choisir "Au format Showdown",
- Cliquer à nouveau sur le select et choisir "D'un autre groupe"

2024-07-12 17:38 UTC, Zodiarche commented
Fixed

2024-07-12 18:16 UTC, Palbolsky approved these changes

2024-07-12 20:48 UTC, AerunDev approved these changes

2024-07-12 20:48 UTC, merged