feat(pokemonBattlresList): add a percent after title
PokemonWorkshop/PokemonStudio pull request #357
Opened 2024-07-10 19:14 UTC by AntoinePoree

Thank you for your contribution to the **Pokémon Studio** repo.

Before submitting this PR into the develop branch, please make sure:

- [x] Your code builds clean without any errors or warnings
- [x] You are following the [Code guidelines](../CodeGuidelines.md)
- [x] You tested your code to make sure it does what it is supposed to do

## Description

I would like to know the sum of the encounter percentages of wild Pokémon in a group
So that I don't have to manually calculate it

## Tests to perform
When no pokemon is present, tag should not be displayed
When some creatures are present, make sure tag is displayed

https://github.com/PokemonWorkshop/PokemonStudio/issues/218

2024-07-10 20:50 UTC, AerunDev approved these changes
Simple et efficace, bien joué à toi ! 😄

2024-07-11 18:59 UTC, NuriYuri approved these changes

2024-07-11 18:59 UTC, NuriYuri commented on src/views/components/pokemonBattler/PokemonBattlerList.tsx
> +          {!!totalEncounterChance && <Tag className="chance">{`${totalEncounterChance}%`}</Tag>}
Comme le reduce commence à 0, il n'est pas nécessaire de tester l'existence de la valeur, ou alors tu peux écrire totalEncounterChance > 0

2024-07-12 16:07 UTC, AntoinePoree commented on src/views/components/pokemonBattler/PokemonBattlerList.tsx
> +          {!!totalEncounterChance && <Tag className="chance">{`${totalEncounterChance}%`}</Tag>}
Yes, rendre la condition plus précise !

2024-07-12 16:10 UTC, Palbolsky requested changes
Le pourcentage ne doit pas s'afficher pour les dresseurs : 

![image](https://github.com/user-attachments/assets/a30e1b31-a820-4d5c-beb7-9350d32f33e0)

2024-07-12 16:30 UTC, AntoinePoree commented
merci Palb, je n'avais pas vu ce bout là !

2024-07-12 18:18 UTC, Palbolsky approved these changes
Parfait bien joué :)

2024-07-12 19:04 UTC, NuriYuri approved these changes

2024-07-12 20:35 UTC, merged