Select research should work even if there are accents
PokemonWorkshop/PokemonStudio pull request #360
Opened 2024-07-12 21:38 UTC by Karbbone

Thank you for your contribution to the **Pokémon Studio** repo.

Before submitting this PR into the develop branch, please make sure:

- [ x] Your code builds clean without any errors or warnings
- [ x] You are following the [Code guidelines](../CodeGuidelines.md)
- [x ] You tested your code to make sure it does what it is supposed to do

## Description

Ne pas rendre obligatoire les accents dans les selects par exemple pour chercher pokédex -> on devait taper le "é" alors que pokedex devrait marché.

## Tests to perform

Les selects de controlbar pour la section base de donnée par exemple. Malgré les différents select j'ai remarqué que seulement le composant StudioDropDown avait ce bug.

2024-07-15 21:14 UTC, AerunDev approved these changes
Testé et approuvé, bien joué ! 😄

2024-07-15 22:46 UTC, Palbolsky requested changes

2024-07-15 22:46 UTC, Palbolsky commented on src/views/components/StudioDropDown.tsx
> +    (option) => normalize(option.value).indexOf(normalize(entry)) !== -1 || normalize(option.label).toLowerCase().indexOf(entryLowerCase) !== -1
La fonction normalize applique déjà `toLowerCase`, inutile de le faire deux fois. :p

2024-07-17 18:04 UTC, Karbbone commented on src/views/components/StudioDropDown.tsx
> +    (option) => normalize(option.value).indexOf(normalize(entry)) !== -1 || normalize(option.label).toLowerCase().indexOf(entryLowerCase) !== -1
Effectivement, : )

2024-07-17 19:53 UTC, Palbolsky commented on src/views/components/StudioDropDown.tsx
> +    (option) => normalize(option.value).indexOf(normalize(entry)) !== -1 || normalize(option.label).toLowerCase().indexOf(entryLowerCase) !== -1
J'ai trouvé un cas qui ne fonctionne pas dans l'éditeur des talents des Pokémon : 

![image](https://github.com/user-attachments/assets/127ee77f-9808-469c-a19e-05774d3242cc)

Ecrire "epine de fer" devrait me permettre de trouver "Épine de Fer".

2024-07-17 20:16 UTC, AerunDev commented on src/views/components/StudioDropDown.tsx
> +    (option) => normalize(option.value).indexOf(normalize(entry)) !== -1 || normalize(option.label).toLowerCase().indexOf(entryLowerCase) !== -1
Peut-être un Select particulier oublié ?

2024-07-17 21:27 UTC, Palbolsky commented on src/views/components/StudioDropDown.tsx
> +    (option) => normalize(option.value).indexOf(normalize(entry)) !== -1 || normalize(option.label).toLowerCase().indexOf(entryLowerCase) !== -1
C'est le select du design system qui est utilisé dans ce composant.

2024-07-18 07:28 UTC, Karbbone commented on src/views/components/StudioDropDown.tsx
> +    (option) => normalize(option.value).indexOf(normalize(entry)) !== -1 || normalize(option.label).toLowerCase().indexOf(entryLowerCase) !== -1
Je pensais l'avoir essayé celui du design system, avec les selects dans la sélection des movespools ou bien je me suis mélangé les pinceaux quand j'ai tout essayé.
Je regarderai ça

2024-07-21 21:46 UTC, Palbolsky commented on src/views/components/StudioDropDown.tsx
> +    (option) => normalize(option.value).indexOf(normalize(entry)) !== -1 || normalize(option.label).toLowerCase().indexOf(entryLowerCase) !== -1
C'est bon pour moi. J'approuve. :)

2024-07-21 21:46 UTC, Palbolsky approved these changes

2024-07-22 19:20 UTC, merged