Add the custom creature form names and descriptions
PokemonWorkshop/PokemonStudio pull request #381
Opened 2024-08-26 12:52 UTC by Palbolsky

## Description

This PR adds the custom creature form names and descriptions to allow the user to choose a form name and description for each form.

CSV files 100066 and 100067 are now used to store form names and descriptions. If these files already exist, the migration will not run and will inform the user of the presence of the file.

## Tests to perform

- [ ] If the CSV files 100066 and 100067 exists before the migration, the migration should be not run ;
- [ ] The user can manage the name of the form ;
- [ ] The user can manage the description of the form (for the form 0, it's the global description of the creature which is used) ;
- [ ] TextIds are freed if a form is deleted ;
- [ ] The creature creation works correctly ;
- [ ] The form creation works correctly ;

## Screenshots

![image](https://github.com/user-attachments/assets/3c63b827-f711-4f10-8c78-087878c392b3)

2024-08-26 20:12 UTC, AerunDev requested changes
Je viens de terminer plusieurs tests, pour voir comment les choses se comportent.
Dans l'ensemble, c'est vraiment cool, et ça va vraiment faciliter les choses pour les utilisateurs, vous avez géré, bien joué ! 😄 
Ça permettra à PSDK de venir se servir du data pour mettre à jour les interfaces comme le Pokédex ou le résumé d'un Pokémon si c'est pertinent.

Je note par contre quelques points qui peuvent être embêtants, et qu'on doit discuter avant de valider totalement : 
- Quand je créé un nouveau Pokémon, puis une nouvelle forme, je remarque que le CSV 100067 contient la description de la forme 1 sans problème, avec copie de la description de base, par contre la description de la forme 0 est remplie de "NewText". Pourrait-on conserver la copie de la description de base pour éviter ça ? Ou alors on ne génère pas la ligne si on est sûr qu'elle ne servira pas ?
- Quand je créé un nouveau Pokémon, le nom de la forme est obligatoire, tout comme quand je tente de la modifier après création. La logique la plus répandue va être de conserver le nom du Pokémon pour la forme de base, et d'avoir un nom différent pour des formes. Est-ce que dans ce contexte c'est judicieux de vouloir forcer l'utilisateur à rentrer deux fois le nom ? Je serais plutôt d'avis de mettre le nom de la forme optionnel pour la création du Pokémon, et si elle n'est pas renseignée, envoyer le nom du Pokémon par défaut.

2024-08-26 20:32 UTC, Palbolsky commented
> Je viens de terminer plusieurs tests, pour voir comment les choses se comportent. Dans l'ensemble, c'est vraiment cool, et ça va vraiment faciliter les choses pour les utilisateurs, vous avez géré, bien joué ! 😄 Ça permettra à PSDK de venir se servir du data pour mettre à jour les interfaces comme le Pokédex ou le résumé d'un Pokémon si c'est pertinent.
> 
> Je note par contre quelques points qui peuvent être embêtants, et qu'on doit discuter avant de valider totalement :
> 
> * Quand je créé un nouveau Pokémon, puis une nouvelle forme, je remarque que le CSV 100067 contient la description de la forme 1 sans problème, avec copie de la description de base, par contre la description de la forme 0 est remplie de "NewText". Pourrait-on conserver la copie de la description de base pour éviter ça ? Ou alors on ne génère pas la ligne si on est sûr qu'elle ne servira pas ?
> * Quand je créé un nouveau Pokémon, le nom de la forme est obligatoire, tout comme quand je tente de la modifier après création. La logique la plus répandue va être de conserver le nom du Pokémon pour la forme de base, et d'avoir un nom différent pour des formes. Est-ce que dans ce contexte c'est judicieux de vouloir forcer l'utilisateur à rentrer deux fois le nom ? Je serais plutôt d'avis de mettre le nom de la forme optionnel pour la création du Pokémon, et si elle n'est pas renseignée, envoyer le nom du Pokémon par défaut.

J'ai apporté les changements pour résoudre les deux problèmes mentionnés.

2024-08-27 20:11 UTC, AerunDev approved these changes

2024-08-27 20:12 UTC, AerunDev commented
C'est nickel pour moi avec les corrections ! 😄
Je vous laisse voir si vous voulez une code review supplémentaire (si oui, contactez quelqu'un de l'équipe), sinon on merge.

2024-08-29 00:10 UTC, Otaku17 approved these changes
Je valide, tout est conforme pour moi.

2024-08-31 16:32 UTC, merged