Allow Studio to migrate the new project
PokemonWorkshop/PokemonStudio pull request #383
Opened 2024-09-03 10:14 UTC by Palbolsky

## Description

Studio is currently unable to migrate a new project because the project.studio file does not exist in the new project archive. Furthermore, since the file does not exist, Studio creates the file and therefore uses the current version of the application. 
No migration can therefore be carried out.

This PR allows Studio to update the project.studio file and retain the latest version of Studio used in the Technical Demo / new project archive. However, this feature is only functional if there is a project.studio in the archive, which is not the case with 1.0.7.

## Note before testing

You need a specific version of the new project archive which contains the project.studio file:
https://mega.nz/file/h5pDQSzQ#EDGI4QkIrxTWbSZ0ntpoK7snUMn9f9uf6wyByIJFz_U

Copy the archive to the root of the Pokémon Studio project.
https://github.com/user-attachments/assets/2c16338d-e938-4150-ab1f-90ca3a010208

In the file `\src\backendTasks\checkDownloadNewProject.ts`, in the line 28, change `needDownload: true` by `needDownload: false`.

## Tests to perform

- [x] Create a new project and check that it opens correctly
- [x] Check that creature form feature works correctly

2024-09-03 16:46 UTC, AntoinePoree commented on src/backendTasks/configureNewProject.ts
> +    if (projectStudioTechnicalDemoParsed.success && newProjectStudioParsed.success) {
si cette condition n'est pas true, on ne passe pas dans le return et on suit un procédé classique, c'est bien le cas, aucune erreur ne peux survenir dans le else ?

2024-09-03 16:54 UTC, Palbolsky commented on src/backendTasks/configureNewProject.ts
> +    if (projectStudioTechnicalDemoParsed.success && newProjectStudioParsed.success) {
Il y a pas de else donc j'ai dû mal à comprendre de quoi tu parles ^^'

L'idée c'est de faire que si le project.studio n'existe pas ou qu'il y a eu un problème dans le parse, Studio crée un project.studio à partir du code (comme c'est le cas actuellement).

2024-09-03 17:34 UTC, AntoinePoree commented on src/backendTasks/configureNewProject.ts
> +    if (projectStudioTechnicalDemoParsed.success && newProjectStudioParsed.success) {
C'était ça la question, vu q'uil n'y a pas de else, si tu rentres dans ton premier if et que tu ne remplis pas les conditions du second if, on part sur un procédé classique, c'est bien ce qu'il faut ? 

Enfaite, c'est ce fonctionnement que j'ai du mal à comprendre vis à vis du second if

2024-09-04 11:54 UTC, AerunDev requested changes
Je viens de tester cette branche en suivant les étapes de test.
Pour info, l'archive fournie n'a pas le bon nom, et contient un dossier au lieu des fichiers directement, du coup il m'a fallu comprendre ça pour avancer.

Lorsque je créé un projet, le projet se créé bien mais au moment du chargement j'ai 830 fichiers non conformes.
Parmi les erreurs Zod : 
```
} Error: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [
      "forms",
      0,
      "formTextId"
    ],
    "message": "Required"
  }
]

} Error: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "bgm"
    ],
    "message": "Expected object, received string"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "bgs"
    ],
    "message": "Expected object, received string"
  }
]

} Error: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "bgm"
    ],
    "message": "Expected object, received string"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "bgs"
    ],
    "message": "Expected object, received string"
  }
]
```

2024-09-04 12:22 UTC, Palbolsky commented
J'avais pas mis le bon lien de téléchargement. Tu peux réessayer ça devrait être bon.

2024-09-06 23:38 UTC, AerunDev approved these changes

2024-09-06 23:38 UTC, AerunDev commented
C'est tout bon pour moi avec la bonne archive ! 😄

2024-09-07 17:57 UTC, AntoinePoree approved these changes

2024-09-07 18:25 UTC, merged