Implementing Input Fields for Center Position Adjustment
PokemonWorkshop/PokemonStudio pull request #395
Opened 2024-10-05 19:03 UTC by Otaku17

## Description

This PR adds input fields to allow the user to easily define and adjust the central position of the elements within the interface. Specifically, it introduces the ability to set the X and Y axes for precise positioning.

## Note before testing

No additional library updates are required for this feature. Ensure you are using the latest version of the project for compatibility.

## Tests to perform

- Verify that the input fields for X and Y axes are available under **Project Settings / Display**.
- Test the functionality by adjusting the X and Y values and ensure that the elements correctly reflect the changes in their central positioning.
- Check for any visual glitches or errors that may occur during adjustments.

2024-10-05 19:08 UTC, Palbolsky requested changes

2024-10-05 19:08 UTC, Palbolsky commented on assets/i18n/en/dashboard_display.json
> +  "tilemap_center": "Center Position",
La majuscule à position est totalement inutile ici. Il y a des typo similaires pour toutes les langues sauf le français.

2024-10-05 19:24 UTC, Otaku17 commented on assets/i18n/en/dashboard_display.json
> +  "tilemap_center": "Center Position",
Donc tu veux que t'enlève la majuscule des autres c'est bien sa

2024-10-05 19:35 UTC, Palbolsky commented on assets/i18n/en/dashboard_display.json
> +  "tilemap_center": "Center Position",
Tu gardes la première majuscule mais pas les autres.

2024-10-07 11:31 UTC, Palbolsky approved these changes

2024-10-08 23:33 UTC, AerunDev approved these changes
Testé et c'est nickel, bien joué ! 😄

2024-10-08 23:36 UTC, merged