Migrate to the latest react flow version
PokemonWorkshop/PokemonStudio pull request #402
Opened 2024-10-19 19:04 UTC by Palbolsky

## Description

This PR update `react-flow-renderer` lib to the latest version. The lib is now named `@xyflow/react`.

Modifications have been made to make the maplink functional.
An error in the import of certain components of the Pokémon page has been corrected (namesake)

## Note before testing

Don't forget to update your lib: `npm i`
If you need to update your npm version: `npm install -g npm@10.9.0`

## Tests to perform

- [ ] The maplink works correctly ;
- [ ] Check that the shortcut with CONTROL click works correctly in the Pokémon page

2024-10-20 12:08 UTC, NuriYuri approved these changes

2024-10-21 15:26 UTC, AntoinePoree approved these changes

2024-10-21 20:47 UTC, AerunDev requested changes
J'ai testé le map link pour être sûr que tout soit bien fonctionnel. Pour moi c'est le cas, bien joué ! 😄 
Je constate juste une régression qui est assez gênante, je te mets les cas de reproduction ici.
J'ai testé sur le Studio en production et ça n'est pas le cas, donc c'est bien l'évolution apportée par cette PR qui la provoque.

## Le canva peut être déplacé lors de la sélection de certains éléments
### Cas 1 - Input de décalage
- ETANT DONNÉ QUE je souhaite modifier le décalage en nombre de tuiles entre deux cartes directement depuis l'input rapide
- LORSQUE je clique et glisse ma souris afin de sélectionner le texte de la valeur contenue dans l'input
- ALORS le canva suit ma souris
### Cas 2 - Node elle-même
- ETANT DONNÉ QUE je souhaite éditer les informations d'une carte liée
- LORSQUE je clique sur la node en dehors de l'input de décalage entre deux cartes et glisse ma souris
- ALORS le canva suit ma souris

2024-10-22 14:43 UTC, Palbolsky commented
> J'ai testé le map link pour être sûr que tout soit bien fonctionnel. Pour moi c'est le cas, bien joué ! 😄 Je constate juste une régression qui est assez gênante, je te mets les cas de reproduction ici. J'ai testé sur le Studio en production et ça n'est pas le cas, donc c'est bien l'évolution apportée par cette PR qui la provoque.

J'ai effectué un changement, pour moi c'est bon mais j'ai pas trop compris le deuxième problème mais il y a moyen qu'il soit aussi corrigé :)

2024-10-22 23:12 UTC, AerunDev approved these changes

2024-10-22 23:13 UTC, AerunDev commented
> J'ai effectué un changement, pour moi c'est bon mais j'ai pas trop compris le deuxième problème mais il y a moyen qu'il soit aussi corrigé :)

Effectivement tout est bon ! 😄

2024-10-22 23:15 UTC, merged