Open a dialog to research the project.studio again if there is an error on loading path
PokemonWorkshop/PokemonStudio pull request #411
Opened 2024-11-12 19:04 UTC by AntoinePoree

… update

Thank you for your contribution to the **Pokémon Studio** repo.

Before submitting this PR into the develop branch, please make sure:

- [X] Your code builds clean without any errors or warnings
- [X] You are following the [Code guidelines](../CodeGuidelines.md)
- [X] You tested your code to make sure it does what it is supposed to do

## Description

Let the user change the path of his project if he get an error with loading it

## Note before testing

Maybe some optimization during the process wil be a plus
## Tests to perform
Change the path of ur porjet, then make it on studio

2024-11-16 11:15 UTC, AerunDev requested changes
Hello! 😄
Je viens de tester le flow utilisateur et c'est parfait comme ça.
Par contre, lorsque je sélectionne le fichier `project.studio` dans le nouveau dossier, le projet ne charge pas.
J'ai regardé les logs et j'ai cette erreur :
```
read-project-metadata/failure Error: ENOENT: no such file or directory, open 'C:\Users\*****\Documents\Pok├®mon Workshop\Technical Demo Play Test\project.studio'
    at Object.readFileSync (node:fs:448:20)
    at t.readFileSync (node:electron/js2c/node_init:2:10245)
    at readProjectMetadata (C:\Users\nicol\Documents\Pok├®mon Workshop\pokemonstudio-dev\.webpack\main\index.js:42878:39)
    at IpcMainImpl.<anonymous> (C:\Users\nicol\Documents\Pok├®mon Workshop\pokemonstudio-dev\.webpack\main\index.js:41702:30)
    at IpcMainImpl.emit (node:events:519:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:85700)
    at WebContents.emit (node:events:519:28)
```
Le fichier existe bien, est-ce que ce ne serait pas un problème de caractère spécial ? Ça fonctionnait avant avec le "é", je préfère préciser.

2024-11-16 16:33 UTC, AntoinePoree commented
> Hello! 😄 Je viens de tester le flow utilisateur et c'est parfait comme ça. Par contre, lorsque je sélectionne le fichier `project.studio` dans le nouveau dossier, le projet ne charge pas. J'ai regardé les logs et j'ai cette erreur :
> 
> ```
> read-project-metadata/failure Error: ENOENT: no such file or directory, open 'C:\Users\*****\Documents\Pok├®mon Workshop\Technical Demo Play Test\project.studio'
>     at Object.readFileSync (node:fs:448:20)
>     at t.readFileSync (node:electron/js2c/node_init:2:10245)
>     at readProjectMetadata (C:\Users\*****\Documents\Pok├®mon Workshop\pokemonstudio-dev\.webpack\main\index.js:42878:39)
>     at IpcMainImpl.<anonymous> (C:\Users\*****\Documents\Pok├®mon Workshop\pokemonstudio-dev\.webpack\main\index.js:41702:30)
>     at IpcMainImpl.emit (node:events:519:28)
>     at WebContents.<anonymous> (node:electron/js2c/browser_init:2:85700)
>     at WebContents.emit (node:events:519:28)
> ```
> 
> Le fichier existe bien, est-ce que ce ne serait pas un problème de caractère spécial ? Ça fonctionnait avant avec le "é", je préfère préciser.

Merci pour ce retour, j'ai pus constater en créant plusieurs projet qu'uniquement le premier projet était mis à jour, le reste des projet n'avait jamais leurs projectPath modifié, donc ce n'était pas un probleme de caractère spéciale, juste une condition qui ne faisait pas son taff 👍

2024-11-16 16:49 UTC, AerunDev commented
Il faut croire que je suis traumatisé par les problèmes de caractères spéciaux avec les OS au boulot 😆 
Je refais un test et go !

2024-11-16 22:39 UTC, AerunDev approved these changes

2024-11-17 19:09 UTC, Palbolsky approved these changes

2024-11-17 19:14 UTC, merged