Implement the trainer additional dialogs
PokemonWorkshop/PokemonStudio pull request #418
Opened 2024-12-08 15:49 UTC by Palbolsky

## Description

This PR implements the trainer additional dialogs feature.
The feature uses the `100069` csv file. A PSDK implementation is required to take advantage of this feature.

The additional dialog object structure added in the trainer:
```typescript
additionalDialogs: {
   condition: z.union([
    z.literal('before_creature_send'),
    z.literal('after_creature_send'),
    z.literal('after_all_actions_choices'),
    z.literal('after_attack_action'),
    z.literal('after_all_turn_actions'),
    z.literal('end_of_battle_turn'),
  ]),
  textId: POSITIVE_OR_ZERO_INT,
}
```
Closes #409 

## Tests to perform

- [ ] The user can change the default dialog (victory and defeat sentence)
- [ ] The user can add an additional dialog
- [ ] The user can change the additional dialogs (condition and text)
- [ ] The user can delete an additional dialog

## Screenshot

![image](https://github.com/user-attachments/assets/52092562-2a15-4f64-88c1-47f14649fb5a)

2024-12-08 20:21 UTC, AntoinePoree requested changes
Good for me 💯

2024-12-08 20:22 UTC, AntoinePoree approved these changes

2024-12-12 23:08 UTC, AerunDev approved these changes
Je viens de tester la PR. C'est franchement nickel, bien joué ! ✨
* Migration OK,
* Gestion des dialogues additionnels OK,
* Gestion des dialogues par défaut OK,
* Parcours utilisateur OK.

En amélioration possibles mais pas obligatoires : 
* Plutôt qu'afficher "---", afficher "Aucun texte renseigné" quand un texte n'existe pas.
* Ajouter peut être une notion de numéro sur la pagination pour qu'on sache où on en est dans la liste, mais à voir plus tard au besoin.

2024-12-12 23:36 UTC, Palbolsky commented
> * Plutôt qu'afficher "---", afficher "Aucun texte renseigné" quand un texte n'existe pas.

J'ai apporté le changement. 😄 

> * Ajouter peut être une notion de numéro sur la pagination pour qu'on sache où on en est dans la liste, mais à voir plus tard au besoin.

Pour moi c'est pas utile, le nom de la condition donne assez d'information ; et ça réduirait l'espace pour afficher le nom de la condition, ce qui pourrait obliger l'utilisateur à utiliser le tooltip plus souvent.

2024-12-14 01:59 UTC, merged