Make sure the user can press ENTER to validate the action in a deletion modal
PokemonWorkshop/PokemonStudio pull request #90
Opened 2023-11-09 17:22 UTC by Karbbone56

## Description

KeyListener on all delete modal, which do the delete action

2023-11-09 19:36 UTC, Palbolsky requested changes

2023-11-09 19:37 UTC, Palbolsky approved these changes
Testé et c'est bon. J'approuve.

2023-11-09 20:30 UTC, NuriYuri commented on src/views/components/deletion/Deletion.tsx
> +  useEffect(() => {
T'as essayé de mettre `autoFocus` sur le <DeleteButton /> (normalement c'est pour les boutons mais ptet que ça fonctionne).

2023-11-09 21:21 UTC, Karbbone56 commented on src/views/components/deletion/Deletion.tsx
> +  useEffect(() => {
J'ai pu essayer maintenant mais il n'y a aucun effet

2023-11-11 10:06 UTC, NuriYuri approved these changes

2023-11-11 10:48 UTC, AntoinePoree approved these changes

2023-11-11 11:02 UTC, merged